In [ ]:
# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

In [ ]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

competitive_data_science_predict_future_sales_path = kagglehub.competition_download('competitive-data-science-predict-future-sales')

print('Data source import complete.')

In [ ]:
import numpy as np
import pandas as pd
import warnings

In [ ]:
warnings.filterwarnings(action='ignore') # 경고 문구 생략

In [ ]:
data_path = '/kaggle/input/competitive-data-science-predict-future-sales/'

In [ ]:
sales_train = pd.read_csv(data_path + 'sales_train.csv')
shops = pd.read_csv(data_path + 'shops.csv')
items = pd.read_csv(data_path + 'items.csv')
item_categories = pd.read_csv(data_path + 'item_categories.csv')
test = pd.read_csv(data_path + 'test.csv')
submission = pd.read_csv(data_path + 'sample_submission.csv')

# 피처 엔지니어링 1: 피처명 한글화

In [ ]:
sales_train = sales_train.rename(columns={'date': '날짜',
                                          'date_block_num': '월ID',
                                          'shop_id': '상점ID',
                                          'item_id': '상품ID',
                                          'item_price': '판매가',
                                          'item_cnt_day': '판매량'})
sales_train.head()

           날짜  월ID  상점ID   상품ID      판매가  판매량
0  02.01.2013    0    59  22154   999.00  1.0
1  03.01.2013    0    25   2552   899.00  1.0
2  05.01.2013    0    25   2552   899.00 -1.0
3  06.01.2013    0    25   2554  1709.05  1.0
4  15.01.2013    0    25   2555  1099.00  1.0

In [ ]:
shops = shops.rename(columns={'shop_name': '상점명',
                              'shop_id': '상점ID'})
shops.head()

                              상점명  상점ID
0   !Якутск Орджоникидзе, 56 фран     0
1   !Якутск ТЦ "Центральный" фран     1
2                Адыгея ТЦ "Мега"     2
3  Балашиха ТРК "Октябрь-Киномир"     3
4        Волжский ТЦ "Волга Молл"     4

In [ ]:
items = items.rename(columns={'item_name': '상품명',
                              'item_id': '상품ID',
                              'item_category_id': '상품분류ID'})
items.head()

                                                 상품명  상품ID  상품분류ID
0          ! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.)         D     0      40
1  !ABBYY FineReader 12 Professional Edition Full...     1      76
2      ***В ЛУЧАХ СЛАВЫ   (UNV)                    D     2      40
3    ***ГОЛУБАЯ ВОЛНА  (Univ)                      D     3      40
4        ***КОРОБКА (СТЕКЛО)                       D     4      40

In [ ]:
item_categories = item_categories.rename(columns={'item_category_name': '상품분류명',
                                                  'item_category_id': '상품분류ID'})
item_categories.head()

                     상품분류명  상품분류ID
0  PC - Гарнитуры/Наушники       0
1         Аксессуары - PS2       1
2         Аксессуары - PS3       2
3         Аксессуары - PS4       3
4         Аксессуары - PSP       4

In [ ]:
test = test.rename(columns={'shop_id': '상점ID',
                            'item_id': '상품ID'})
test.head()

   ID  상점ID  상품ID
0   0     5  5037
1   1     5  5320
2   2     5  5233
3   3     5  5232
4   4     5  5268

# 피처 엔지니어링 2: 데이터 다운캐스팅

- 다운캐스팅: 더 작은 데이터 타입으로 변환하는 작업 <br>
=> 불필요하게 데이터가 큰 타입이라면 작은 타입으로 변환해 할당함 <br>
=> 메모리 낭비를 막고 훈련속도가 빨라짐

In [ ]:
def downcast(df, verbose=True):
    start_mem = df.memory_usage().sum() / 1024**2

    for col in df.columns:
        dtype_name = df[col].dtype.name
        if dtype_name == 'object':
            pass
        elif dtype_name == 'bool':
            df[col] = df[col].astype('int8')
        elif dtype_name.startswith('int') or (df[col].round() == df[col]).all():
            df[col] = pd.to_numeric(df[col], downcast='integer')
        else:
            df[col] = pd.to_numeric(df[col], downcast='float')

    end_mem = df.memory_usage().sum() / 1024**2

    if verbose:
        print('{:.1f}% 압축됨'.format(100 * (start_mem - end_mem) / start_mem))

    return df

In [ ]:
all_df = [sales_train, shops, items, item_categories, test]

for df in all_df:
    df = downcast(df)

54.2% 압축됨
38.5% 압축됨
54.2% 압축됨
39.8% 압축됨
70.8% 압축됨

# 피처 엔지니어링 3: 데이터 조합 생성

In [ ]:
from itertools import product

In [ ]:
train = []

In [ ]:
# 월ID, 상점ID, 상품ID 조합 생성
for i in sales_train['월ID'].unique():
    all_shop = sales_train.loc[sales_train['월ID']==i, '상점ID'].unique()
    all_item = sales_train.loc[sales_train['월ID']==i, '상품ID'].unique()
    train.append(np.array(list(product([i], all_shop, all_item))))

In [ ]:
idx_features = ['월ID', '상점ID', '상품ID'] # 기준 피처

In [ ]:
# 리스트 타입인 train을 DataFrame 타입으로 변환
train = pd.DataFrame(np.vstack(train), columns=idx_features)
train

          월ID  상점ID   상품ID
0           0    59  22154
1           0    59   2552
2           0    59   2554
3           0    59   2555
4           0    59   2564
...       ...   ...    ...
10913845   33    21   7635
10913846   33    21   7638
10913847   33    21   7640
10913848   33    21   7632
10913849   33    21   7440

[10913850 rows x 3 columns]

# 피처 엔지니어링 4: 타깃값(월간 판매량) 추가

In [ ]:
# idx_features를 기준으로 그룹화해 판매량 합 구하기
group = sales_train.groupby(idx_features).agg({'판매량': 'sum'})

group = group.reset_index()

# 피처명을 '판매량'애서 '월간 판매량'으로 변경
group = group.rename(columns={'판매량': '월간 판매량'})

group

         월ID  상점ID   상품ID  월간 판매량
0          0     0     32       6
1          0     0     33       3
2          0     0     35       1
3          0     0     43       1
4          0     0     51       2
...      ...   ...    ...     ...
1609119   33    59  22087       6
1609120   33    59  22088       2
1609121   33    59  22091       1
1609122   33    59  22100       1
1609123   33    59  22102       1

[1609124 rows x 4 columns]

In [ ]:
train = train.merge(group, on=idx_features, how='left')
train

          월ID  상점ID   상품ID  월간 판매량
0           0    59  22154     1.0
1           0    59   2552     NaN
2           0    59   2554     NaN
3           0    59   2555     NaN
4           0    59   2564     NaN
...       ...   ...    ...     ...
10913845   33    21   7635     NaN
10913846   33    21   7638     NaN
10913847   33    21   7640     NaN
10913848   33    21   7632     NaN
10913849   33    21   7440     NaN

[10913850 rows x 4 columns]

# 가비지 컬렉션

- 가비지 컬렉션: 할당 메모리 중 더는 사용하지 않는 영역 해제 (메모리 효율적으로 사용 가능)

In [ ]:
import gc # 가비지 컬렉터

In [ ]:
del group # 더는 사용하지 않는 변수 지정
gc.collect(); # 가비지 컬렉션 수행

# 피처 엔지니어링 5: 테스트 데이터 이어붙이기

In [ ]:
test['월ID'] = 34

In [ ]:
# train과 test 이어붙이기
all_data = pd.concat([train, test.drop('ID', axis=1)],
                     ignore_index=True, # 기존 인덱스 무시(0부터 새로 시작)
                     keys=idx_features) # 이어붙이는 기준이 되는 피처

In [ ]:
all_data = all_data.fillna(0)
all_data

          월ID  상점ID   상품ID  월간 판매량
0           0    59  22154     1.0
1           0    59   2552     0.0
2           0    59   2554     0.0
3           0    59   2555     0.0
4           0    59   2564     0.0
...       ...   ...    ...     ...
11128045   34    45  18454     0.0
11128046   34    45  16188     0.0
11128047   34    45  15757     0.0
11128048   34    45  19648     0.0
11128049   34    45    969     0.0

[11128050 rows x 4 columns]

# 피처 엔지니어링 6: 나머지 데이터 병합(최종 데이터 생성)

In [ ]:
all_data = all_data.merge(shops, on='상점ID', how='left')
all_data = all_data.merge(items, on='상품ID', how='left')
all_data = all_data.merge(item_categories, on='상품분류ID', how='left')

In [ ]:
# 데이터 다운캐스팅
all_data = downcast(all_data)

31.1% 압축됨

In [ ]:
all_data.head()

,월ID,상점ID,상품ID,월간 판매량,상점명,상품명,상품분류ID,상품분류명
0,0,59,22154,1,"Ярославль ТЦ ""Альтаир""",ЯВЛЕНИЕ 2012 (BD),37,Кино - Blu-Ray
1,0,59,2552,0,"Ярославль ТЦ ""Альтаир""",DEEP PURPLE The House Of Blue Light LP,58,Музыка - Винил
2,0,59,2554,0,"Ярославль ТЦ ""Альтаир""",DEEP PURPLE Who Do You Think We Are LP,58,Музыка - Винил
3,0,59,2555,0,"Ярославль ТЦ ""Альтаир""",DEEP PURPLE 30 Very Best Of 2CD (Фирм.),56,Музыка - CD фирменного производства
4,0,59,2564,0,"Ярославль ТЦ ""Альтаир""",DEEP PURPLE Perihelion: Live In Concert DVD (К...,59,Музыка - Музыкальное видео

In [ ]:
del shops, items, item_categories
gc.collect();

In [ ]:
all_data = all_data.drop(['상점명', '상품명', '상품분류명'], axis=1)

# 피처 엔지니어링 7: 마무리

In [ ]:
# 훈련 데이터 (피처)
X_train = all_data[all_data['월ID'] < 33]
X_train = X_train.drop(['월간 판매량'], axis=1)

# 검증 데이터 (피처)
X_valid = all_data[all_data['월ID'] == 33]
X_valid = X_valid.drop(['월간 판매량'], axis=1)

# 테스트 데이터 (피처)
X_test = all_data[all_data['월ID'] == 34]
X_test = X_test.drop(['월간 판매량'], axis=1)

In [ ]:
# 훈련 데이터 (타깃값)
y_train = all_data[all_data['월ID'] < 33]['월간 판매량']
y_train = y_train.clip(0, 20) # 타깃값을 0 ~ 20로 제한

# 검증 데이터 (타깃값)
y_valid = all_data[all_data['월ID'] == 33]['월간 판매량']
y_valid = y_valid.clip(0, 20)

In [ ]:
y_train

0           1
1           0
2           0
3           0
4           0
           ..
10675673    0
10675674    0
10675675    0
10675676    0
10675677    0
Name: 월간 판매량, Length: 10675678, dtype: int16

In [ ]:
del all_data
gc.collect();

# 모델 훈련 및 성능 검증

In [ ]:
import lightgbm as lgb

In [ ]:
# LightGBM용 하이퍼파라미터
params = {'metric': 'rmse', # 평가지표 = rmse
          'num_leaves': 255,
          'learning_rate': 0.01,
          'force_col_wise': True,
          'random_state': 10}

In [ ]:
# 범주형 피처 설정
cat_features = ['상점ID', '상품분류ID']

In [ ]:
# LightGBM용 훈련 및 검증 데이터 셋
dtrain = lgb.Dataset(X_train, y_train)
dvalid = lgb.Dataset(X_valid, y_valid)

In [ ]:
# LightGBM 모델 훈련
lgb_model = lgb.train(params=params,
                      train_set=dtrain,
                      num_boost_round=500,
                      valid_sets=(dtrain, dvalid),
                      categorical_feature=cat_features,
                      callbacks=[
                              lgb.log_evaluation(50) # verbose_eval=50
                      ])

[LightGBM] [Info] Total Bins 426
[LightGBM] [Info] Number of data points in the train set: 10675678, number of used features: 4
[LightGBM] [Info] Start training from score 0.299125
[50]	training's rmse: 1.14777	valid_1's rmse: 1.06755
[100]	training's rmse: 1.11425	valid_1's rmse: 1.0386
[150]	training's rmse: 1.09673	valid_1's rmse: 1.02671
[200]	training's rmse: 1.08573	valid_1's rmse: 1.02027
[250]	training's rmse: 1.07722	valid_1's rmse: 1.01661
[300]	training's rmse: 1.0698	valid_1's rmse: 1.0138
[350]	training's rmse: 1.06317	valid_1's rmse: 1.01084
[400]	training's rmse: 1.05734	valid_1's rmse: 1.00936
[450]	training's rmse: 1.05224	valid_1's rmse: 1.00818
[500]	training's rmse: 1.04792	valid_1's rmse: 1.00722

# 예측 및 결과 제출

In [ ]:
preds = lgb_model.predict(X_test).clip(0, 20)

In [ ]:
submission['item_cnt_month'] = preds
submission.to_csv('submission.csv', index=False)

In [ ]:
del X_train, y_train, X_valid, y_valid, X_test, lgb_model, dtrain, dvalid,
gc.collect();

# 선서